apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-hello-deployment
  namespace: ns-nginx 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-hello
  template:
    metadata:
      labels:
        app: nginx-hello
    spec:
      containers : 
      - name: nginx-hello
        image: nginxdemos/hello:latest # Imagen del hello-world extraida desde dockerhub para demos helloworld en texto plano https://hub.docker.com/r/nginxdemos/hello/
        ports:
        - containerPort: 80
        resources: 
          requests:
            memory: "64Mi"
            cpu: "250m"    
          limits:
            memory: "128Mi" 
            cpu: "500m"     
